Adding test confirmation

diff --git a/.github/workflows/docker_build.yaml b/.github/workflows/docker_build.yaml
--- a/.github/workflows/docker_build.yaml
+++ b/.github/workflows/docker_build.yaml
@@ -22,12 +22,14 @@ jobs:
           include:
             - app: betydb2geojson
               parameters: https://terraref.ncsa.illinois.edu/bety bety_plots.geojson
-              test_results: if [[ -f "bety_plots.geojson" ]]; then exit 0; else echo "App failed"; exit 1; fi;
+              test_results: if [[ -f "bety_plots.geojson" ]]; then echo "Test success"; exit 0; else echo "App failed"; exit 1; fi;
     steps:
       - name: Fetch source code
         uses: actions/checkout@v2
         id: fetch-source
       - name: Build docker image
         run: docker build -t test ./
-      - name: run test
+      - name: Run test
         run: docker run --rm -v `pwd`:/mnt test:latest run ${{ matrix.app }} ${{ matrix.parameters }}
+      - name: Check results
+        run: ${{ matrix.test_results }}
