Changing csv key index for new csv contents

diff --git a/.github/workflows/docker_build_test.yaml b/.github/workflows/docker_build_test.yaml
--- a/.github/workflows/docker_build_test.yaml
+++ b/.github/workflows/docker_build_test.yaml
@@ -84,7 +84,7 @@ jobs:
               echo "CSV file contents"
               cat './outputs/canopycover.csv'
               curl -sfL https://raw.githubusercontent.com/aswinkarthik/csvdiff/master/install.sh | sh -s -- -b ./csvdiff
-              if [[ "$(./csvdiff/csvdiff './test_data/canopycover.csv' './outputs/canopycover.csv' --columns 1 --primary-key 4 --format rowmark 2>&1 | grep -A 5 'Rows:' | wc -l  | tr -d '[:space:]')" == "1" ]]; then echo "Test merge_csv content matches expected"; exit 0; else echo "App failed - merge_csv contents mismatch from test_data/canopycover.csv"; exit 1; fi;
+              if [[ "$(./csvdiff/csvdiff './test_data/canopycover.csv' './outputs/canopycover.csv' --columns 1 --primary-key 3 --format rowmark 2>&1 | grep -A 5 'Rows:' | wc -l  | tr -d '[:space:]')" == "1" ]]; then echo "Test merge_csv content matches expected"; exit 0; else echo "App failed - merge_csv contents mismatch from test_data/canopycover.csv"; exit 1; fi;
     steps:
       - name: Install Python 3.7
         uses: actions/setup-python@v2
