Added shp2geojson testing

diff --git a/.github/workflows/docker_build.yaml b/.github/workflows/docker_build.yaml
--- a/.github/workflows/docker_build.yaml
+++ b/.github/workflows/docker_build.yaml
@@ -18,17 +18,25 @@ jobs:
     name: Build docker container
     strategy:
       matrix:
-          app: [betydb2geojson]
+          app: [betydb2geojson, shp2geojson]
           include:
             - app: betydb2geojson
               parameters: https://terraref.ncsa.illinois.edu/bety /mnt/bety_plots.geojson
-              test_results: if [[ -f "bety_plots.geojson" ]]; then echo "Test success"; exit 0; else echo "App failed"; exit 1; fi;
+              test_results: if [[ -f "bety_plots.geojson" ]]; then echo "Test betydb2geojson success"; exit 0; else echo "App failed - betydb2geojson"; exit 1; fi;
+            - app: shp2geojson
+              parameters: /mnt/plot_shapes.shp /mnt/shp_plots.geojson
+              test_results: if [[ -f "shp_plots.geojson" ]]; then echo "Test shp2geojson success"; exit 0; else echo "App failed - shp2geojson"; exit 1; fi;
     steps:
       - name: Fetch source code
         uses: actions/checkout@v2
         id: fetch-source
       - name: Build docker image
         run: docker build -t test ./
+      - name: Checking for additional downloads
+        if: ${{ matrix.app  == 'shp2geojson' }}
+        run: curl -X GET https://de.cyverse.org/dl/d/3C8A23C0-F77A-4598-ADC4-874EB265F9B0/scif_test_data.tar.gz > scif_test_data.tar.gz
+             tar xvzf scif_test_data.tar.gz -C "./"
+             ls -l
       - name: Run test
         run: docker run --rm -v `pwd`:/mnt test:latest run ${{ matrix.app }} ${{ matrix.parameters }}
       - name: Folder listing
