Fixcing workflow detail check

diff --git a/.github/workflows/docker_build_test.yaml b/.github/workflows/docker_build_test.yaml
--- a/.github/workflows/docker_build_test.yaml
+++ b/.github/workflows/docker_build_test.yaml
@@ -24,18 +24,22 @@ jobs:
           - app: betydb2geojson
             parameter_json: .github/workflows/app_testing.json
             test_results: if [[ -f "outputs/plots.geojson" ]]; then echo "Test betydb2geojson success"; exit 0; else echo "App failed - betydb2geojson"; exit 1; fi;
+            test_results_quality: if [[ "$(diff --ignore-all-space './test_data/plots_betydb.geojson' './outputs/plots.geojson')" == "" ]]; then echo "Test betydb2json content matches expected"; exit 0; else echo "App failed - betydb2json contents mismatch from test_data/plots_betydb.geojson"; exit 1; fi;
           - app: shp2geojson
             tar_gz_file: https://de.cyverse.org/dl/d/3C8A23C0-F77A-4598-ADC4-874EB265F9B0/scif_test_data.tar.gz
             parameter_json: .github/workflows/app_testing.json
             test_results: if [[ -f "outputs/plots.geojson" ]]; then echo "Test shp2geojson success"; exit 0; else echo "App failed - shp2geojson"; exit 1; fi;
+            test_results_quality: if [[ "$(diff --ignore-all-space './test_data/plots_shapefile.geojson' './outputs/plots.geojson')" == "" ]]; then echo "Test shp2geojson content matches expected"; exit 0; else echo "App failed - shp2geojson contents mismatch from test_data/plots_shapefile.geojson"; exit 1; fi;
           - app: soilmask
             tar_gz_file: https://de.cyverse.org/dl/d/3C8A23C0-F77A-4598-ADC4-874EB265F9B0/scif_test_data.tar.gz
             parameter_json: .github/workflows/app_testing.json
             test_results: if [[ -f "outputs/orthomosaicmask.tif" ]]; then echo "Test soilmask success"; exit 0; else echo "App failed - soilmask"; exit 1; fi;
+            test_results_quality: if [[ "$(diff './test_data/orthomosaicmask.tif' './outputs/orthomosaicmask.tif')" == "" ]]; then echo "Test soilmask content matches expected"; exit 0; else echo "App failed - soilmask contents mismatch from test_data/orthomosaicmask.tif"; exit 1; fi;
           - app: plotclip
             tar_gz_file: https://de.cyverse.org/dl/d/BC328D44-621B-41B6-A662-0CD7F2D4C0EE/ci_plotclip_test_data.tar.gz
             parameter_json: .github/workflows/app_testing.json
             test_results: chmod +x .github/workflows/check_plotclip_app.sh && ./.github/workflows/check_plotclip_app.sh ${PWD}/outputs
+            test_results_quality: python3 './.github/workflows/check_plotclip_details.py' ./test_data ./outputs
           - app: find_files2json
             tar_gz_file: https://de.cyverse.org/dl/d/ADBEEBDE-E000-4FCB-AE74-62047ED4DD8E/ci_find_files2json_test_data.tar.gz
             parameter_json: .github/workflows/app_testing.json
@@ -140,4 +144,4 @@ jobs:
       - name: CSV contents check
         run: |
           curl -sfL https://raw.githubusercontent.com/aswinkarthik/csvdiff/master/install.sh | sh -s -- -b ./csvdiff
-          if [[ "$(./csvdiff/csvdiff /test_data/canopycover.csv /outputs/canopycover.csv --columns 1 --primary-key 4 --format rowmark 2>&1 | grep -A 5 'Rows:' | wc -l  | tr -d '[:space:]')" == '1']]; then echo "Canopy Cover value compare success"; exit 0; else echo "Workflow failed - canopy cover value compare"; exit 1; fi;
+          if [[ "$(./csvdiff/csvdiff /test_data/canopycover.csv /outputs/canopycover.csv --columns 1 --primary-key 4 --format rowmark 2>&1 | grep -A 5 'Rows:' | wc -l  | tr -d '[:space:]')" == "1" ]]; then echo "Canopy Cover value compare success"; exit 0; else echo "Workflow failed - canopy cover value compare"; exit 1; fi;
